---
- name: make sure dnf-plugins.core installed
  dnf:
    name: dnf-plugins-core
    state: present
    
- name: install docker repository
  command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  