---
- name: Disable excludes
  dnf:
    disable_excludes: all

- name: Make sure containerd.io is installed
  dnf:
    name: containerd.io
    state: latest

- name: Install Docker 
  dnf:
    name: docker-ce
    state: latest

- name: start docker
  service:
    name: docker
    state: started