---
- name: Disable Selinux
  import_tasks: selinux.yml
  
- name: Import Docker CE repo when distro is Redhat since they made weird changes
  import_tasks: add-repo.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Update all packages
  import_tasks: update.yml

- name: Install Docker CE
  import_tasks: docker.yml



# - name: Change Firewalld to work with Docker
#   command: firewall-cmd --zone=trusted --change-interface=docker0
  
# - name: Make it permanent
#   command: firewall-cmd --zone=trusted --add-masquerade --permanent
  
# - name: Reload it  
#   command: firewall-cmd --reload

